apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b0thqc-mu-go
  janus-idp.io/tekton: b0thqc-mu-go
  backstage.io/kubernetes-id: b0thqc-mu-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b0thqc-mu-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
