apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: b0thqc-mu-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: b0thqc-mu-go 
  name: b0thqc-mu-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: b0thqc-mu-go 
